name: bari_koi_map_with_autocomplete
description: Barikoi App.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  logger: ^2.1.0
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  go_router: ^13.2.1
  flutter_screenutil: ^5.9.0
  injectable: ^2.3.5
  get_it: ^7.6.7
  envied: ^0.5.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  stack_trace: ^1.11.1
  maplibre_gl:
    git:
      url: https://github.com/maplibre/flutter-maplibre-gl.git
      ref: main
  flutter_zoom_drawer: ^3.2.0

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  isar_generator: ^3.1.0+1
  lint: ^2.3.0

flutter:
  uses-material-design: true
